/** Built-in studio presets: decorative starter styles across grids, render modes and symmetry. */

import type { PresetSeed } from './preset-configs'
import { SWEETIE_16 } from './preset-configs'

export const STUDIO_PRESETS: PresetSeed[] = [
  {
    name: 'Neon Metaballs',
    id: 'builtin.neon-metaballs',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 2,
      palette: ['#00e5ff', '#ff2e88', '#ffe600', '#7c4dff', '#00ff9d', '#ff6d00'],
      renderMode: 'metaball',
      connectivity: 'corner-bridge',
      metaball: { strength: 62, perColor: true, quality: 6 },
      bg: '#0b0f1c',
      symmetry: { mode: 'kaleido', n: 6, showGuides: true },
    },
  },
  {
    name: 'Game Boy',
    id: 'builtin.gameboy',
    input: {
      gridType: 'square',
      cols: 20,
      rows: 18,
      sub: 1,
      palette: ['#0f380f', '#306230', '#8bac0f', '#9bbc0f'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 0.92, sizeY: 0.92 },
      bg: '#9bbc0f',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Bubblegum',
    id: 'builtin.bubblegum',
    input: {
      gridType: 'square',
      cols: 20,
      rows: 20,
      sub: 2,
      palette: [
        '#ff8fab',
        '#ffb3c6',
        '#ffd6a5',
        '#fdffb6',
        '#b9fbc0',
        '#90dbf4',
        '#a78bfa',
        '#ffffff',
      ],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.5, sizeX: 0.85, sizeY: 0.85 },
      bg: '#fff5fa',
      symmetry: { mode: 'quad', n: 8, showGuides: true },
    },
  },
  {
    name: 'Blueprint',
    id: 'builtin.blueprint',
    input: {
      gridType: 'square',
      cols: 28,
      rows: 28,
      sub: 1,
      palette: ['#cfe8ff', '#7fb8ff', '#ffffff', '#4a90d9'],
      renderMode: 'outline',
      connectivity: 'corner-bridge',
      style: { convexRadius: 0.12, concaveRadius: 0.08 },
      bg: '#0a2f5c',
      symmetry: { mode: 'none', n: 8, showGuides: true },
    },
  },
  {
    name: 'Kaleido Bloom',
    id: 'builtin.kaleido-bloom',
    input: {
      gridType: 'hex',
      cols: 22,
      rows: 22,
      sub: 1,
      palette: ['#f72585', '#7209b7', '#3a0ca3', '#4361ee', '#4cc9f0', '#ffd60a'],
      renderMode: 'metaball',
      connectivity: 'corner-bridge',
      metaball: { strength: 55, perColor: true, quality: 6 },
      bg: '#12081f',
      symmetry: { mode: 'radial', n: 12, showGuides: false },
    },
  },
  {
    name: 'Retro Chamfer',
    id: 'builtin.retro-chamfer',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 1,
      palette: SWEETIE_16,
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.3, sizeX: 0.9, sizeY: 0.9, cornerStyle: 'chamfer' },
      bg: '#1a1c2c',
      symmetry: { mode: 'diag8', n: 8, showGuides: true },
    },
  },
  {
    name: 'Mandala',
    id: 'builtin.mandala',
    input: {
      gridType: 'radial',
      cols: 16,
      rows: 14,
      sub: 1,
      palette: ['#ffbe0b', '#fb5607', '#ff006e', '#8338ec', '#3a86ff'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.18, sizeX: 0.95, sizeY: 0.95 },
      bg: '#160e24',
      symmetry: { mode: 'radial', n: 16, showGuides: false },
    },
  },
  {
    name: 'Sticker Pop',
    id: 'builtin.sticker-pop',
    input: {
      gridType: 'square',
      cols: 20,
      rows: 20,
      sub: 1,
      palette: ['#e63946', '#2a9d8f', '#4361ee', '#ffb703', '#7209b7', '#f72585'],
      renderMode: 'outline',
      connectivity: 'corner',
      style: { convexRadius: 0.42, concaveRadius: 0.3, sizeX: 0.9, sizeY: 0.9 },
      bg: '#ffffff',
      symmetry: { mode: 'mirrorX', n: 8, showGuides: true },
    },
  },
  {
    name: 'Vaporwave',
    id: 'builtin.vaporwave',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 20,
      sub: 2,
      palette: ['#ff71ce', '#01cdfe', '#05ffa1', '#b967ff', '#fffb96', '#e8437f'],
      renderMode: 'outline',
      connectivity: 'corner-bridge',
      style: { convexRadius: 0.25, concaveRadius: 0.15 },
      bg: '#160e2e',
      symmetry: { mode: 'mirrorX', n: 8, showGuides: true },
    },
  },
  {
    name: 'Circuit Board',
    id: 'builtin.circuit',
    input: {
      gridType: 'square',
      cols: 28,
      rows: 28,
      sub: 1,
      palette: ['#00ff9d', '#00b8d9', '#a7f070', '#0f5132', '#343a40'],
      renderMode: 'outline',
      connectivity: 'corner-bridge',
      style: { convexRadius: 0.12, concaveRadius: 0.06 },
      bg: '#04140f',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Ice Garden',
    id: 'builtin.ice-garden',
    input: {
      gridType: 'hex',
      cols: 20,
      rows: 20,
      sub: 1,
      palette: ['#e0f2fe', '#a5f3fc', '#7fb8ff', '#3b82f6', '#1e3a8a', '#ffffff'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.5, sizeX: 0.92, sizeY: 0.92 },
      bg: '#0c1b33',
      symmetry: { mode: 'mirrorX', n: 8, showGuides: false },
    },
  },
  {
    name: 'Ember Field',
    id: 'builtin.ember-field',
    input: {
      gridType: 'radial',
      cols: 16,
      rows: 14,
      sub: 1,
      palette: ['#ff6d00', '#ff2e00', '#ffc300', '#fed7aa', '#7c2d12'],
      renderMode: 'metaball',
      connectivity: 'corner-bridge',
      metaball: { strength: 58, perColor: true, quality: 5 },
      bg: '#1a0a05',
      symmetry: { mode: 'radial', n: 10, showGuides: false },
    },
  },
  {
    name: 'Film Noir',
    id: 'builtin.film-noir',
    input: {
      gridType: 'square',
      cols: 32,
      rows: 32,
      sub: 1,
      palette: ['#e8e8e8', '#000000', '#8a8a8a', '#3d3d3d'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 0.95, sizeY: 0.95 },
      bg: '#101010',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Candy Rush',
    id: 'builtin.candy-rush',
    input: {
      gridType: 'triangle',
      cols: 24,
      rows: 20,
      sub: 1,
      palette: ['#ff5d8f', '#ffb3c6', '#ffe066', '#7ce577', '#5bc0eb', '#f187fb'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.35, sizeX: 0.9, sizeY: 0.9 },
      bg: '#fff0f6',
      symmetry: { mode: 'quad', n: 8, showGuides: true },
    },
  },
  {
    name: 'Terminal',
    id: 'builtin.terminal',
    input: {
      gridType: 'square',
      cols: 32,
      rows: 24,
      sub: 1,
      palette: ['#00ff41', '#0fff50', '#39ff14', '#003b00', '#052b0d'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 0.9, sizeY: 0.9 },
      bg: '#001100',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Pastel Hex',
    id: 'builtin.pastel-hex',
    input: {
      gridType: 'hex',
      cols: 22,
      rows: 22,
      sub: 1,
      palette: ['#ffd6e0', '#ffefcf', '#d1f5d3', '#cfe8ff', '#e5d4ff', '#fefae0'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.25, sizeX: 0.92, sizeY: 0.92 },
      bg: '#fdf6f9',
      symmetry: { mode: 'mirrorX', n: 8, showGuides: true },
    },
  },
  {
    name: 'Sunflower',
    id: 'builtin.sunflower',
    input: {
      gridType: 'radial',
      cols: 18,
      rows: 16,
      sub: 1,
      palette: ['#ffd60a', '#ffb703', '#fb8500', '#bc6c25', '#603808'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.2, sizeX: 0.95, sizeY: 0.95 },
      bg: '#2b1d0e',
      symmetry: { mode: 'radial', n: 18, showGuides: true },
    },
  },
  {
    name: 'Chalk Outline',
    id: 'builtin.chalk-outline',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 1,
      palette: ['#f0ede4', '#b9c0c9', '#8a9199', '#d7d2c0'],
      renderMode: 'outline',
      connectivity: 'corner',
      style: { convexRadius: 0.15, concaveRadius: 0.1 },
      bg: '#22332d',
      symmetry: { mode: 'mirrorX', n: 8, showGuides: false },
    },
  },
  {
    name: 'Aurora',
    id: 'builtin.aurora',
    input: {
      gridType: 'hex',
      cols: 20,
      rows: 20,
      sub: 2,
      palette: ['#00ffc8', '#00b4d8', '#7b2ff7', '#48f0a0', '#1c6e8c'],
      renderMode: 'metaball',
      connectivity: 'corner-bridge',
      metaball: { strength: 66, perColor: false, quality: 6 },
      bg: '#06121f',
      symmetry: { mode: 'mirrorX', n: 8, showGuides: false },
    },
  },
  {
    name: 'Pixel Dungeon',
    id: 'builtin.pixel-dungeon',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 1,
      palette: SWEETIE_16,
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 0.95, sizeY: 0.95 },
      bg: '#1a1c2c',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Koi Pond',
    id: 'builtin.koi-pond',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 3,
      palette: ['#ffffff', '#e63946', '#f4a261', '#457b9d', '#94d2bd', '#f1faee'],
      renderMode: 'metaball',
      connectivity: 'corner-bridge',
      metaball: { strength: 45, perColor: true, quality: 5 },
      bg: '#123a47',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Stained Glass',
    id: 'builtin.stained-glass',
    input: {
      gridType: 'square',
      cols: 22,
      rows: 22,
      sub: 1,
      palette: ['#e63946', '#2a9d8f', '#457b9d', '#ffc300', '#7209b7', '#f7f4ea'],
      renderMode: 'outline',
      connectivity: 'corner',
      style: { convexRadius: 0.3, concaveRadius: 0.25 },
      bg: '#0d0d12',
      symmetry: { mode: 'quad', n: 8, showGuides: true },
    },
  },
  {
    name: 'Dither Study',
    id: 'builtin.dither-study',
    input: {
      gridType: 'square',
      cols: 28,
      rows: 28,
      sub: 1,
      palette: ['#26262b', '#e6e6e6'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.5, sizeX: 0.6, sizeY: 0.6 },
      bg: '#e6e6e6',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
]
