/** Built-in retro machine presets: vintage computers and terminals. */

import type { PresetSeed } from './preset-configs'

export const RETRO_PRESETS: PresetSeed[] = [
  {
    name: 'Teletext',
    id: 'builtin.teletext',
    input: {
      gridType: 'square',
      cols: 32,
      rows: 24,
      sub: 1,
      palette: [
        '#000000',
        '#ff0000',
        '#00ff00',
        '#ffff00',
        '#0000ff',
        '#ff00ff',
        '#00ffff',
        '#ffffff',
      ],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 0.9, sizeY: 0.9 },
      bg: '#000000',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'CGA Terminal',
    id: 'builtin.cga-terminal',
    input: {
      gridType: 'square',
      cols: 32,
      rows: 20,
      sub: 1,
      palette: ['#000000', '#55ffff', '#ff55ff', '#ffffff'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 0.7, sizeY: 0.9 },
      bg: '#000000',
      symmetry: { mode: 'mirrorX', n: 8, showGuides: true },
    },
  },
  {
    name: 'Macintosh Classic',
    id: 'builtin.macintosh-classic',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 1,
      palette: ['#000000', '#444444', '#888888', '#bbbbbb', '#ffffff'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.1, sizeX: 0.95, sizeY: 0.95 },
      bg: '#ffffff',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Gruvbox Study',
    id: 'builtin.gruvbox-study',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 1,
      palette: [
        '#282828',
        '#3c3836',
        '#504945',
        '#665c54',
        '#bdae93',
        '#d5c4a1',
        '#ebdbb2',
        '#fbf1c7',
        '#cc241d',
        '#b16286',
        '#98971a',
        '#d79921',
        '#458588',
        '#689d6a',
        '#d65d0e',
        '#b8bb26',
      ],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.15, sizeX: 0.9, sizeY: 0.9 },
      bg: '#282828',
      symmetry: { mode: 'quad', n: 8, showGuides: true },
    },
  },
]
