/** Built-in texture study presets: grain and grunge surface effects. */

import type { PresetSeed } from './preset-configs'

export const TEXTURE_PRESETS: PresetSeed[] = [
  {
    name: 'Vintage Print',
    id: 'builtin.vintage-print',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 1,
      palette: ['#3d2b1f', '#7a5230', '#b08968', '#d4a373', '#606c38', '#bc4749'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.12, sizeX: 0.9, sizeY: 0.9 },
      texture: { effect: 'grain', amount: 55, scale: 1.1, seed: 1948 },
      bg: '#f2e8cf',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Rust Bloom',
    id: 'builtin.rust-bloom',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 1,
      palette: ['#20201d', '#8c2f1b', '#b4552d', '#d98e4a', '#3f3a34'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.2, sizeX: 1, sizeY: 1 },
      texture: {
        effect: 'grunge',
        amount: 72,
        scale: 1.5,
        sizeMin: 0.14,
        sizeMax: 0.5,
        shape: 'chip',
        edge: 65,
        dist: 'voronoi',
        gap: 0.16,
        angle: 45,
        seed: 7134,
      },
      bg: '#20201d',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Concrete',
    id: 'builtin.concrete',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 1,
      palette: ['#4e4a44', '#d7d3cb', '#a8a29a', '#7a756d'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.08, sizeX: 1, sizeY: 1 },
      texture: {
        effect: 'grain',
        amount: 78,
        scale: 1.2,
        sizeMin: 0.08,
        sizeMax: 0.3,
        shape: 'square',
        edge: 100,
        dist: 'perlin',
        gap: 0.1,
        angle: 45,
        seed: 5150,
      },
      bg: '#4e4a44',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Dot Matrix',
    id: 'builtin.dot-matrix',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 1,
      palette: ['#1d2126', '#39c2d7', '#f4f7f5', '#e0a526'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.5, sizeX: 1, sizeY: 1 },
      texture: {
        effect: 'halftone',
        amount: 55,
        scale: 0.9,
        sizeMin: 0.12,
        sizeMax: 0.35,
        shape: 'dot',
        edge: 100,
        dist: 'scatter',
        gap: 0,
        angle: 45,
        seed: 808,
      },
      bg: '#f4f7f5',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
]
