/** Built-in form study presets: one cell shape per preset, with tuned size and palette. */

import type { PresetSeed } from './preset-configs'

export const FORMS_PRESETS: PresetSeed[] = [
  {
    name: 'Polka Dots',
    id: 'builtin.form-dots',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 1,
      palette: ['#22223b', '#4a4e69', '#9a8c98', '#c9ada7', '#f2e9e4'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: {
        shape: 'circle',
        shapeParams: { thickness: 0.25, points: 5, rotation: 0 },
        sizeX: 0.82,
        sizeY: 0.82,
      },
      bg: '#f2e9e4',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Rings',
    id: 'builtin.form-rings',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 1,
      palette: ['#0d1b2a', '#1b493b', '#5fa8d3', '#cae9ff', '#ffd166'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: {
        shape: 'ring',
        shapeParams: { thickness: 0.18, points: 5, rotation: 0 },
        sizeX: 0.96,
        sizeY: 0.96,
      },
      bg: '#0d1b2a',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Cross Stitch',
    id: 'builtin.form-crosses',
    input: {
      gridType: 'square',
      cols: 28,
      rows: 28,
      sub: 1,
      palette: ['#2d2016', '#8c5e3c', '#c98f4e', '#e8c896', '#5c4033'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: {
        shape: 'xCross',
        shapeParams: { thickness: 0.34, points: 5, rotation: 0 },
        radius: 0.06,
        sizeX: 0.92,
        sizeY: 0.92,
      },
      bg: '#2d2016',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Star Field',
    id: 'builtin.form-stars',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 1,
      palette: ['#0b0d17', '#f4d35e', '#ee964b', '#f95738', '#3d5a80'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: {
        shape: 'star',
        shapeParams: { thickness: 0.3, points: 5, rotation: 0 },
        sizeX: 0.95,
        sizeY: 0.95,
      },
      bg: '#0b0d17',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Mosaic',
    id: 'builtin.form-mosaic',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 1,
      palette: ['#31572c', '#4f772d', '#90a955', '#ecf39e', '#132a13'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: {
        shape: 'hexagon',
        shapeParams: { thickness: 0.25, points: 5, rotation: 0 },
        sizeX: 0.9,
        sizeY: 0.9,
      },
      bg: '#132a13',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Sweethearts',
    id: 'builtin.form-hearts',
    input: {
      gridType: 'square',
      cols: 22,
      rows: 22,
      sub: 1,
      palette: ['#641220', '#85182a', '#a71e34', '#bd1e36', '#fcd5ce'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: {
        shape: 'heart',
        shapeParams: { thickness: 0.25, points: 5, rotation: 0 },
        sizeX: 0.84,
        sizeY: 0.84,
      },
      bg: '#fcd5ce',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
]
