/** Built-in texture study presets: grain/grunge surfaces and the procedural pattern family. */

import type { PresetSeed } from './configs'

export const TEXTURE_PRESETS: PresetSeed[] = [
  {
    name: 'Vintage Print',
    id: 'builtin.vintage-print',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 1,
      palette: ['#3d2b1f', '#7a5230', '#b08968', '#d4a373', '#606c38', '#bc4749'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.12, sizeX: 0.9, sizeY: 0.9 },
      texture: { effect: 'grain', amount: 55, scale: 1.1, seed: 1948 },
      bg: '#f2e8cf',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Rust Bloom',
    id: 'builtin.rust-bloom',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 1,
      palette: ['#20201d', '#8c2f1b', '#b4552d', '#d98e4a', '#3f3a34'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.2, sizeX: 1, sizeY: 1 },
      texture: {
        effect: 'grunge',
        amount: 72,
        scale: 1.5,
        sizeMin: 0.14,
        sizeMax: 0.5,
        shape: 'chip',
        edge: 65,
        dist: 'voronoi',
        gap: 0.16,
        angle: 45,
        seed: 7134,
      },
      bg: '#20201d',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Concrete',
    id: 'builtin.concrete',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 1,
      palette: ['#4e4a44', '#d7d3cb', '#a8a29a', '#7a756d'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.08, sizeX: 1, sizeY: 1 },
      texture: {
        effect: 'grain',
        amount: 78,
        scale: 1.2,
        sizeMin: 0.08,
        sizeMax: 0.3,
        shape: 'square',
        edge: 100,
        dist: 'perlin',
        gap: 0.1,
        angle: 45,
        seed: 5150,
      },
      bg: '#4e4a44',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Dot Matrix',
    id: 'builtin.dot-matrix',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 1,
      palette: ['#1d2126', '#39c2d7', '#f4f7f5', '#e0a526'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.5, sizeX: 1, sizeY: 1 },
      texture: {
        effect: 'halftone',
        amount: 55,
        scale: 0.9,
        sizeMin: 0.12,
        sizeMax: 0.35,
        shape: 'dot',
        edge: 100,
        dist: 'scatter',
        gap: 0,
        angle: 45,
        seed: 808,
      },
      bg: '#f4f7f5',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Bayer Print',
    id: 'builtin.bayer-print',
    input: {
      gridType: 'square',
      cols: 28,
      rows: 28,
      sub: 1,
      palette: ['#141414', '#f0ede4', '#c9331b', '#2b6e8f'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 1, sizeY: 1 },
      texture: {
        effect: 'grain',
        amount: 88,
        scale: 1.3,
        sizeMin: 0.1,
        sizeMax: 0.22,
        shape: 'square',
        dist: 'bayer',
        gap: 0.06,
        gapMode: 'figure',
        seed: 404,
      },
      bg: '#f0ede4',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Sunburst Fade',
    id: 'builtin.sunburst-fade',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 1,
      palette: ['#2d1e2f', '#e56b2d', '#f4c95d', '#6a8d73'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.5, sizeX: 1, sizeY: 1 },
      texture: {
        effect: 'grain',
        amount: 80,
        scale: 1.6,
        sizeMin: 0.1,
        sizeMax: 0.3,
        shape: 'dot',
        dist: 'sunburst',
        gap: 0.12,
        gapMode: 'figure',
        seed: 909,
      },
      bg: '#2d1e2f',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Mermaid',
    id: 'builtin.mermaid',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 1,
      palette: ['#0f3d3e', '#3c9d9b', '#85cdca', '#e8f1f2', '#d9a5b3'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.3, sizeX: 1, sizeY: 1 },
      texture: {
        effect: 'grain',
        amount: 85,
        scale: 1.5,
        sizeMin: 0.12,
        sizeMax: 0.28,
        shape: 'ring',
        dist: 'scales',
        even: true,
        gap: 0.08,
        gapMode: 'figure',
        seed: 1717,
      },
      bg: '#0f3d3e',
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
]
