/** Built-in print presets: halftone screen effects on paper-like palettes. */

import type { PresetSeed } from './configs'

export const PRINT_PRESETS: PresetSeed[] = [
  {
    name: 'Newspaper',
    id: 'builtin.newspaper',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 2,
      palette: ['#1c1c1c', '#4a4a4a', '#8a8a8a', '#f4f1ea'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 1, sizeY: 1 },
      bg: '#f4f1ea',
      texture: { effect: 'halftone', amount: 55, scale: 1.6, angle: 45 },
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Comic Pop',
    id: 'builtin.comic-pop',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 2,
      palette: ['#d7263d', '#1b998b', '#ffcd38', '#2e294e', '#ffffff'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0.5, sizeX: 0.94, sizeY: 0.94 },
      bg: '#fffdf7',
      texture: { effect: 'halftone', amount: 65, scale: 2.2, angle: 15, seed: 7 },
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Ink Blobs',
    id: 'builtin.ink-blobs',
    input: {
      gridType: 'square',
      cols: 22,
      rows: 22,
      sub: 2,
      palette: ['#101014', '#2b2d42', '#8d99ae', '#edf2f4'],
      renderMode: 'metaball',
      connectivity: 'corner-bridge',
      metaball: { strength: 55, perColor: true, quality: 5 },
      bg: '#edf2f4',
      texture: {
        effect: 'halftone',
        amount: 80,
        scale: 1.2,
        angle: 45,
        jitter: 40,
        variation: 45,
        merge: 70,
        wobble: 55,
        seed: 11,
      },
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Worn Poster',
    id: 'builtin.worn-poster',
    input: {
      gridType: 'square',
      cols: 26,
      rows: 26,
      sub: 2,
      palette: ['#e07a5f', '#3d405b', '#81b29a', '#f2cc8f', '#f4f1de'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 1, sizeY: 1 },
      bg: '#f4f1de',
      texture: {
        effect: 'halftone',
        amount: 65,
        scale: 1.8,
        angle: 25,
        jitter: 30,
        variation: 40,
        dropout: 35,
        spray: 45,
        ramp: 30,
        seed: 23,
      },
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Silk Screen',
    id: 'builtin.silk-screen',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 2,
      palette: ['#0f0e17', '#ff8906', '#f25f4c', '#e53170', '#fffffe'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 1, sizeY: 1 },
      bg: '#fffffe',
      texture: { effect: 'halftone', amount: 40, scale: 2.6, angle: 25 },
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Sunfade',
    id: 'builtin.sunfade',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 2,
      palette: ['#ffba08', '#faa307', '#f48c06', '#dc2f02', '#6a040f'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 1, sizeY: 1 },
      bg: '#fff3b0',
      texture: { effect: 'halftone', amount: 80, scale: 1.4, angle: 135, ramp: 95, seed: 5 },
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Vintage Photo',
    id: 'builtin.vintage-photo',
    input: {
      gridType: 'square',
      cols: 30,
      rows: 30,
      sub: 2,
      palette: ['#3b3128', '#6f5e46', '#a8906f', '#d4bd9c', '#efe6d5'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 1, sizeY: 1 },
      bg: '#efe6d5',
      texture: {
        effect: 'halftone',
        amount: 70,
        scale: 1.2,
        angle: 45,
        jitter: 25,
        variation: 35,
        wobble: 30,
        dropout: 20,
        spray: 25,
        seed: 42,
      },
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
  {
    name: 'Dot Gradient',
    id: 'builtin.dot-gradient',
    input: {
      gridType: 'square',
      cols: 24,
      rows: 24,
      sub: 2,
      palette: ['#03045e', '#0077b6', '#00b4d8', '#90e0ef', '#caf0f8'],
      renderMode: 'pixels',
      connectivity: 'edge',
      style: { radius: 0, sizeX: 1, sizeY: 1 },
      bg: '#caf0f8',
      texture: { effect: 'halftone', amount: 90, scale: 1.3, angle: 90, ramp: 100, seed: 9 },
      symmetry: { mode: 'none', n: 8, showGuides: false },
    },
  },
]
